name: Build Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: true
        default: 'PCSX ReARMed Release'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: false
        type: boolean

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Install build dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libsdl1.2-dev libasound2-dev libpng-dev libz-dev
        
    - name: Configure
      run: |
        ./configure
        
    - name: Build
      run: |
        make -j$(nproc)
        
    - name: Create release package
      run: |
        make rel
        
    - name: Get version info
      id: version
      run: |
        VERSION=$(git describe --always --tags HEAD)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "archive_name=pcsx_rearmed_${VERSION}.zip" >> $GITHUB_OUTPUT
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pcsx-rearmed-linux-${{ steps.version.outputs.version }}
        path: pcsx_rearmed_*.zip
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.release_tag }}
        name: ${{ inputs.release_name }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        files: |
          pcsx_rearmed_*.zip
        body: |
          ## PCSX ReARMed Linux Build
          
          This release contains a pre-built Linux version of PCSX ReARMed.
          
          **Version:** ${{ steps.version.outputs.version }}
          
          ### Contents:
          - `pcsx` - Main executable
          - `plugins/` - GPU and SPU plugins
          - `bios/` - BIOS directory (add your own BIOS files here)
          - `skin/` - UI skin files
          - Documentation files
          
          ### Requirements:
          - Linux x86_64
          - SDL 1.2
          - ALSA/PulseAudio for audio
          - OpenGL ES for GPU acceleration (optional)
          
          ### Installation:
          1. Extract the zip file
          2. Run `./pcsx` from the extracted directory
          3. Place your PlayStation BIOS file in the `bios/` directory
          4. Use the menu to load and play games
          
          Built from commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}