name: Build Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: true
        default: 'PCSX ReARMed Release'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        default: false
        type: boolean

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        
    - name: Install build dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libsdl1.2-dev libasound2-dev libpng-dev libz-dev
        
    - name: Configure
      run: |
        DUMP_CONFIG_LOG=1 ./configure
        
    - name: Build
      run: |
        make -j$(nproc)
        
    - name: Create release package
      run: |
        make rel
        
    - name: Get version and package info
      id: version
      run: |
        VERSION=$(git describe --always --tags HEAD)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Find the generated package
        PACKAGE=$(ls pcsx_rearmed_*.zip | head -1)
        NEW_PACKAGE="pcsx_rearmed_${VERSION}_linux-x86_64.zip"
        
        # Rename to include platform info
        if [ "$PACKAGE" != "$NEW_PACKAGE" ]; then
          mv "$PACKAGE" "$NEW_PACKAGE"
        fi
        
        echo "package=$NEW_PACKAGE" >> $GITHUB_OUTPUT
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pcsx-rearmed-linux-x86_64-${{ steps.version.outputs.version }}
        path: ${{ steps.version.outputs.package }}
        retention-days: 30
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.release_tag }}
        name: ${{ inputs.release_name }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        files: |
          ${{ steps.version.outputs.package }}
        body: |
          ## PCSX ReARMed Release
          
          This release contains a pre-built Linux x86_64 version of PCSX ReARMed.
          
          **Version:** ${{ steps.version.outputs.version }}
          **Built from commit:** ${{ github.sha }}
          
          ### Contents:
          - `pcsx` - Main executable
          - `plugins/` - GPU and SPU plugins (GPU NEON, GPU P.E.Op.S., GPU Unai, GPU OpenGL ES)
          - `spunull.so` - Null SPU plugin
          - `bios/` - BIOS directory (add your own BIOS files here)
          - `skin/` - UI skin files
          - Documentation files (`readme.txt`, `COPYING`)
          
          ### System Requirements:
          - Linux x86_64 (Intel/AMD 64-bit)
          - SDL 1.2 library (`libsdl1.2debian` package on Ubuntu/Debian)
          - ALSA/PulseAudio for audio (`libasound2` or `pulseaudio` packages)
          - Optional: OpenGL ES for GPU acceleration
          
          ### Installation:
          1. Download and extract the zip file
          2. Install dependencies: `sudo apt-get install libsdl1.2debian libasound2-dev`
          3. Run `./pcsx` from the extracted directory
          4. Place your PlayStation BIOS file in the `bios/` directory
          5. Use the menu to load and play games
          
          ### Features:
          - ARM-optimized MIPS->x86_64 recompiler for high performance
          - Multiple GPU plugins for compatibility and performance
          - NEON-optimized graphics rendering
          - Save state support
          - Memory card support
          - CD image format support (.bin/.cue, .iso, .pbp, .cbn)
          - CHD format support
          
          ### Notes:
          - This build uses the Lightrec dynamic recompiler for optimal performance
          - GPU NEON plugin is included for high-performance graphics
          - For ARM devices (Raspberry Pi, etc.), check the existing CI builds or compile from source
          
          For more information, see the [repository README](https://github.com/ioma8/pcsx_rearmed/blob/master/README.md).
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
